cmake_minimum_required(VERSION 3.25)

if(NOT APPLE)
    message(FATAL_ERROR "These workflow tests require macOS plutil and zsh")
endif()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(root "${VEKT_BINARY_DIR}/cmake/plugin workflow ${nonce}")
set(tool_log "${root}/tools.log")
set(stub_failure "")
set(au_registry "aufx Ravv Tava  -  Thomas Vaags: Rav|aufx Glmr Tava  -  Thomas Vaags: Glimmer|aumu Kobr Tava  -  Thomas Vaags: Mono|aumu Flnt Tava  -  Thomas Vaags: Flint")
file(MAKE_DIRECTORY "${root}/bin" "${root}/scripts" "${root}/packaging/macos")
foreach(script IN ITEMS scripts/build-au.sh scripts/validate-release.sh packaging/macos/validate-plugins.sh)
    configure_file("${VEKT_SOURCE_DIR}/${script}" "${root}/${script}" COPYONLY)
endforeach()

function(create_stub tool)
    if(tool STREQUAL "plutil")
        file(WRITE "${root}/bin/${tool}" [=[#!/bin/zsh
[[ "${argv[-1]}" == "${VEKT_SCRIPT_LOG:h}/"* ]] || exit 1
exec /usr/bin/plutil "$@"
]=])
    else()
        file(WRITE "${root}/bin/${tool}" [=[#!/bin/zsh
print -r -- "${0:t}: ${(j: :)@}" >> "$VEKT_SCRIPT_LOG"
[[ "${0:t} $1" != "auval -a" ]] || print -rl -- ${(s:|:)VEKT_STUB_AU_REGISTRY}
[[ "${VEKT_STUB_FAIL_TOOL:-}" != "${0:t}" ]] || exit 47
]=])
    endif()
    file(CHMOD "${root}/bin/${tool}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endfunction()
foreach(tool IN ITEMS cmake pluginval auval codesign plutil)
    create_stub("${tool}")
endforeach()

function(create_bundles product target title au_type au_subtype)
    # Products live in plugins/<product>; Mono still in plugins/vekt_mono.
    if(product STREQUAL "mono")
        set(folder vekt_mono)
    else()
        set(folder "${product}")
    endif()
    set(artifact_root "${root}/build/release/plugins/${folder}/${target}_artefacts/Release")
    string(JSON plist SET "{}" CFBundleIdentifier "\"com.thomasvaags.${product}\"")
    foreach(format IN ITEMS VST3 AU)
        if(format STREQUAL "AU")
            set(extension component)
        else()
            set(extension vst3)
        endif()
        set(bundle "${artifact_root}/${format}/${title}.${extension}")
        file(MAKE_DIRECTORY "${bundle}/Contents/MacOS")
        file(WRITE "${bundle}/Contents/Info.plist" "${plist}")
        file(WRITE "${bundle}/Contents/MacOS/${title}" "test binary for ${product}\n")
    endforeach()
    string(JSON component SET "{}" type "\"${au_type}\"")
    string(JSON component SET "${component}" subtype "\"${au_subtype}\"")
    string(JSON component SET "${component}" manufacturer "\"Tava\"")
    string(JSON plist SET "${plist}" AudioComponents "[${component}]")
    set(au_bundle "${artifact_root}/AU/${title}.component")
    set(vst3_bundle "${artifact_root}/VST3/${title}.vst3")
    file(WRITE "${au_bundle}/Contents/Info.plist" "${plist}")
    set(installed_bundle "${root}/home/Library/Audio/Plug-Ins/Components/${title}.component")
    file(REMOVE_RECURSE "${installed_bundle}")
    file(COPY "${au_bundle}/" DESTINATION "${installed_bundle}")
    set(${product}_au "${au_bundle}" PARENT_SCOPE)
    set(${product}_vst3 "${vst3_bundle}" PARENT_SCOPE)
    set(${product}_installed "${installed_bundle}" PARENT_SCOPE)
endfunction()

function(run_workflow expected_exit expected_text script)
    file(WRITE "${tool_log}" "")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env "HOME=${root}/home" "PATH=${root}/bin"
            "VEKT_SCRIPT_LOG=${tool_log}" "VEKT_STUB_FAIL_TOOL=${stub_failure}"
            "VEKT_STUB_AU_REGISTRY=${au_registry}" "VEKT_AU_REGISTRATION_TIMEOUT=0"
            /bin/zsh "${root}/${script}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL expected_exit)
        message(FATAL_ERROR "${script}: expected exit ${expected_exit}, got ${result}\n${output}${error}\nFixtures: ${root}")
    endif()
    string(FIND "${output}${error}" "${expected_text}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "${script}: missing '${expected_text}'\n${output}${error}\nFixtures: ${root}")
    endif()
    file(READ "${tool_log}" log)
    set(last_log "${log}" PARENT_SCOPE)
endfunction()

function(require_log text)
    string(FIND "${last_log}" "${text}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing tool invocation '${text}'\n${last_log}")
    endif()
endfunction()

function(require_no_tools)
    if(NOT last_log STREQUAL "")
        message(FATAL_ERROR "Tools ran after failed preflight: ${last_log}")
    endif()
endfunction()

create_bundles(rav Rav "Rav" aufx Ravv)
create_bundles(glimmer Glimmer "Glimmer" aufx Glmr)
create_bundles(mono VektMono "Mono" aumu Kobr)
create_bundles(flint Flint "Flint" aumu Flnt)

run_workflow(0 "" scripts/build-au.sh)
require_log("cmake: --preset dev")
require_log("cmake: --build --preset dev --target Rav_AU Glimmer_AU VektMono_AU Flint_AU")
run_workflow(0 "" scripts/build-au.sh --release)
require_log("cmake: --preset release")
require_log("cmake: --build --preset release --target Rav_AU Glimmer_AU VektMono_AU Flint_AU")
foreach(product IN ITEMS rav glimmer mono flint)
    run_workflow(0 "PASS: ${product} validators" scripts/validate-release.sh "${product}")
    require_log("codesign: --verify --deep --strict --verbose=2 ${${product}_au}")
    require_log("pluginval: --validate ${${product}_vst3} --strictness-level 10")
    if(product STREQUAL "flint")
        require_log("pluginval: --validate AudioUnit:Synths/aumu,Flnt,Tava --strictness-level 10")
        require_log("auval: -v aumu Flnt Tava")
    elseif(product STREQUAL "mono")
        require_log("pluginval: --validate AudioUnit:Synths/aumu,Kobr,Tava --strictness-level 10")
        require_log("auval: -v aumu Kobr Tava")
    elseif(product STREQUAL "glimmer")
        require_log("pluginval: --validate AudioUnit:Effects/aufx,Glmr,Tava --strictness-level 10")
        require_log("auval: -v aufx Glmr Tava")
    else()
        require_log("pluginval: --validate AudioUnit:Effects/aufx,Ravv,Tava --strictness-level 10")
        require_log("auval: -v aufx Ravv Tava")
    endif()
endforeach()
run_workflow(64 "Unknown product:" scripts/validate-release.sh invalid)
require_no_tools()
run_workflow(1 "VST3 bundle not found:" packaging/macos/validate-plugins.sh rav "${root}/missing.vst3" "${rav_au}")
require_no_tools()
file(WRITE "${root}/not-a-bundle.vst3" "not a directory")
run_workflow(1 "VST3 bundle not found:" packaging/macos/validate-plugins.sh rav "${root}/not-a-bundle.vst3" "${rav_au}")
require_no_tools()
run_workflow(1 "Bundle product mismatch:" packaging/macos/validate-plugins.sh rav "${mono_vst3}" "${rav_au}")
require_no_tools()

file(WRITE "${rav_installed}/Contents/MacOS/Rav" "stale installed binary\n")
run_workflow(1 "Installed AU component differs" scripts/validate-release.sh rav)
require_no_tools()
create_bundles(rav Rav "Rav" aufx Ravv)
set(duplicate "${root}/home/Library/Audio/Plug-Ins/Components/Duplicate.component")
file(COPY "${rav_au}/" DESTINATION "${duplicate}")
run_workflow(1 "found 2" scripts/validate-release.sh rav)
require_no_tools()
file(REMOVE_RECURSE "${duplicate}")
file(RENAME "${rav_installed}" "${root}/uninstalled.component")
run_workflow(1 "found 0" scripts/validate-release.sh rav)
require_no_tools()
file(RENAME "${root}/uninstalled.component" "${rav_installed}")

set(au_registry_complete "${au_registry}")
set(au_registry "aumu Kobr Tava  -  Thomas Vaags: Mono")
run_workflow(1 "rav AU (aufx Ravv Tava) not registered after 0s" scripts/validate-release.sh rav)
require_log("pluginval: --validate ${rav_vst3} --strictness-level 10")
if(last_log MATCHES "AudioUnit:|auval: -v")
    message(FATAL_ERROR "AU validators ran before registration: ${last_log}")
endif()
set(au_registry "${au_registry_complete}")

file(REMOVE "${root}/bin/auval")
run_workflow(69 "SKIP: auval is required" scripts/validate-release.sh rav)
require_no_tools()
create_stub(auval)
foreach(tool IN ITEMS codesign pluginval auval)
    set(stub_failure "${tool}")
    run_workflow(47 "" scripts/validate-release.sh rav)
    if(NOT tool STREQUAL "auval" AND last_log MATCHES "auval:")
        message(FATAL_ERROR "auval ran after a failed validator: ${last_log}")
    endif()
    if(tool STREQUAL "codesign" AND last_log MATCHES "pluginval:")
        message(FATAL_ERROR "pluginval ran after a failed signature check: ${last_log}")
    endif()
endforeach()
file(REMOVE_RECURSE "${root}")
message(STATUS "PASS: macOS plugin workflow routing and failure handling (stub tools; no runtime acceptance)")
