# Every registered Catch2 test case carries an owner tag (a product or framework module), and a case named after a
# product ("Rav ...", "Glimmer ...", "Kobber ...", "Flint ...") carries that product's tag, so label runs (ctest -L,
# docs/VERIFICATION_SPEED.md) cannot miss it. A hidden case ([.] or [!hide]) must carry no owner tag: Catch2 runs a
# hidden case whenever a tag it carries is named, so "vekt_dsp_tests [compat]" would otherwise run the capture cases
# and rewrite the fixtures. A test macro the policy cannot parse fails it.
# Usage: cmake -DVEKT_TESTS_DIR=<tests> -P TestTagPolicy.cmake
if(NOT VEKT_TESTS_DIR)
	message(FATAL_ERROR "VEKT_TESTS_DIR is required")
endif()

set(owner_tags rav glimmer kobber flint dsp ui presets state plugin-support compat audio-lab audio-analysis framework)
set(ws "[ \t\r\n]*")
set(string_literal "\"[^\"]*\"")
set(macro_start "[^A-Za-z0-9_](TEST_CASE|TEST_CASE_METHOD|SCENARIO|TEMPLATE_TEST_CASE|TEMPLATE_PRODUCT_TEST_CASE)\\(")
file(GLOB_RECURSE sources "${VEKT_TESTS_DIR}/*.cpp" "${VEKT_TESTS_DIR}/*.h" "${VEKT_TESTS_DIR}/*.mm")
set(offenders "")
set(count 0)
set(hidden_count 0)
foreach(source IN LISTS sources)
	file(READ "${source}" content)
	string(PREPEND content "\n")
	string(REGEX MATCHALL "${macro_start}" macros "${content}")
	string(REGEX MATCHALL
		"[^A-Za-z0-9_](TEST_CASE|SCENARIO|TEMPLATE_TEST_CASE|TEMPLATE_PRODUCT_TEST_CASE)\\(${ws}${string_literal}${ws},${ws}${string_literal}"
		cases "${content}")
	string(REGEX MATCHALL
		"[^A-Za-z0-9_]TEST_CASE_METHOD\\(${ws}[A-Za-z0-9_:<>]+${ws},${ws}${string_literal}${ws},${ws}${string_literal}"
		method_cases "${content}")
	list(APPEND cases ${method_cases})
	list(LENGTH macros macro_count)
	list(LENGTH cases case_count)
	if(NOT macro_count EQUAL case_count)
		file(RELATIVE_PATH relative "${VEKT_TESTS_DIR}" "${source}")
		string(APPEND offenders
			"\n  ${relative}: ${macro_count} test macros but ${case_count} with a literal name and tags")
	endif()
	foreach(case IN LISTS cases)
		string(REGEX MATCHALL "${string_literal}" literals "${case}")
		list(GET literals 0 name)
		list(GET literals 1 tags)
		string(REGEX REPLACE "^\"(.*)\"$" "\\1" name "${name}")
		string(REGEX REPLACE "^\"(.*)\"$" "\\1" tags "${tags}")
		set(owners "")
		foreach(owner IN LISTS owner_tags)
			string(FIND "${tags}" "[${owner}]" at)
			if(NOT at EQUAL -1)
				list(APPEND owners "${owner}")
			endif()
		endforeach()
		string(FIND "${tags}" "[." dot_hidden)
		string(FIND "${tags}" "[!hide]" bang_hidden)
		if(NOT dot_hidden EQUAL -1 OR NOT bang_hidden EQUAL -1)
			math(EXPR hidden_count "${hidden_count} + 1")
			if(owners)
				string(APPEND offenders "\n  hidden case carries an owner tag (${owners}): ${name} ${tags}")
			endif()
			continue()
		endif()
		math(EXPR count "${count} + 1")
		if(NOT owners)
			string(APPEND offenders "\n  no owner tag: ${name} ${tags}")
		endif()
		foreach(product IN ITEMS Rav Glimmer Kobber Flint)
			string(TOLOWER "${product}" tag)
			if(name MATCHES "^${product}[ A-Z]" AND NOT tags MATCHES "\\[${tag}\\]")
				string(APPEND offenders "\n  missing [${tag}]: ${name} ${tags}")
			endif()
		endforeach()
	endforeach()
endforeach()

if(count EQUAL 0)
	message(FATAL_ERROR "No TEST_CASE found under ${VEKT_TESTS_DIR}")
endif()
if(offenders)
	message(FATAL_ERROR "Test cases need an owner tag (${owner_tags}) and their product's tag, hidden ones none:${offenders}")
endif()
message(STATUS "${count} registered test cases carry owner and product tags; ${hidden_count} hidden cases carry none")
