include(CMakeParseArguments)

function(vekt_validate_factory_preset_path path description)
	if(IS_ABSOLUTE "${path}" OR NOT path MATCHES "^([A-Za-z0-9][A-Za-z0-9 ._-]*/)*[A-Za-z0-9][A-Za-z0-9 ._-]*\\.vektpreset$")
		message(FATAL_ERROR "Invalid ${description}: ${path}")
	endif()
endfunction()

function(vekt_add_factory_presets)
	cmake_parse_arguments(ARG "" "TARGET;NAMESPACE;HEADER_NAME;PRESET_ROOT;ORDER_FILE;LOCK_FILE;MANIFEST_HEADER;MANIFEST_NAMESPACE" "" ${ARGN})
	foreach(required TARGET NAMESPACE HEADER_NAME PRESET_ROOT ORDER_FILE LOCK_FILE MANIFEST_HEADER MANIFEST_NAMESPACE)
		if(NOT ARG_${required})
			message(FATAL_ERROR "vekt_add_factory_presets requires ${required}")
		endif()
	endforeach()

	file(STRINGS "${ARG_ORDER_FILE}" orderedPaths)
	set(manifestPaths)
	foreach(path IN LISTS orderedPaths)
		string(STRIP "${path}" path)
		if(path STREQUAL "" OR path MATCHES "^#")
			continue()
		endif()
		vekt_validate_factory_preset_path("${path}" "factory preset manifest entry")
		list(FIND manifestPaths "${path}" duplicateIndex)
		if(NOT duplicateIndex EQUAL -1)
			message(FATAL_ERROR "Duplicate factory preset manifest entry: ${path}")
		endif()
		if(NOT EXISTS "${ARG_PRESET_ROOT}/${path}")
			message(FATAL_ERROR "Factory preset manifest entry does not exist: ${path}")
		endif()
		list(APPEND manifestPaths "${path}")
	endforeach()

	file(STRINGS "${ARG_LOCK_FILE}" lockedPaths)
	set(releasedPaths)
	foreach(path IN LISTS lockedPaths)
		string(STRIP "${path}" path)
		if(path STREQUAL "" OR path MATCHES "^#")
			continue()
		endif()
		vekt_validate_factory_preset_path("${path}" "factory preset release lock entry")
		list(FIND releasedPaths "${path}" duplicateIndex)
		if(NOT duplicateIndex EQUAL -1)
			message(FATAL_ERROR "Duplicate factory preset release lock entry: ${path}")
		endif()
		list(FIND manifestPaths "${path}" manifestIndex)
		if(manifestIndex EQUAL -1)
			message(FATAL_ERROR "Released factory preset is missing from the order manifest: ${path}")
		endif()
		if(NOT EXISTS "${ARG_PRESET_ROOT}/${path}")
			message(FATAL_ERROR "Released factory preset does not exist: ${path}")
		endif()
		list(APPEND releasedPaths "${path}")
	endforeach()
	set(releasedIndex 0)
	foreach(path IN LISTS releasedPaths)
		list(GET manifestPaths ${releasedIndex} orderedPath)
		if(NOT path STREQUAL orderedPath)
			message(FATAL_ERROR "Factory preset order must preserve the released program bank: ${path}")
		endif()
		math(EXPR releasedIndex "${releasedIndex} + 1")
	endforeach()

	file(GLOB_RECURSE discoveredPaths CONFIGURE_DEPENDS RELATIVE "${ARG_PRESET_ROOT}" "${ARG_PRESET_ROOT}/*.vektpreset")
	list(SORT discoveredPaths)
	foreach(path IN LISTS discoveredPaths)
		vekt_validate_factory_preset_path("${path}" "discovered factory preset path")
	endforeach()
	set(resourcePaths ${manifestPaths})
	foreach(path IN LISTS discoveredPaths)
		list(FIND manifestPaths "${path}" manifestIndex)
		if(manifestIndex EQUAL -1)
			list(APPEND resourcePaths "${path}")
		endif()
	endforeach()

	set(resourceNames)
	set(manifestEntries "#pragma once\n\n#include <vekt/presets/EmbeddedFactoryPresets.h>\n\nnamespace ${ARG_MANIFEST_NAMESPACE}\n{\ninline constexpr vekt::presets::EmbeddedFactoryPreset resources[] {\n")
	foreach(path IN LISTS resourcePaths)
		get_filename_component(fileName "${path}" NAME)
		get_filename_component(folder "${path}" DIRECTORY)
		string(REGEX REPLACE "[^A-Za-z0-9]" "_" resourceName "${fileName}")
		list(FIND resourceNames "${resourceName}" duplicateResourceIndex)
		if(NOT duplicateResourceIndex EQUAL -1)
			message(FATAL_ERROR "Factory preset filenames must have unique generated resource names: ${fileName}")
		endif()
		list(APPEND resourceNames "${resourceName}")
		string(APPEND manifestEntries "\t{ \"${resourceName}\", \"${folder}\" },\n")
	endforeach()

	string(APPEND manifestEntries "};\n}\n")
	set(generatedDirectory "${CMAKE_CURRENT_BINARY_DIR}/factory_presets")
	file(MAKE_DIRECTORY "${generatedDirectory}")
	file(WRITE "${generatedDirectory}/${ARG_MANIFEST_HEADER}" "${manifestEntries}")

	set(resourceFiles)
	foreach(path IN LISTS resourcePaths)
		list(APPEND resourceFiles "${ARG_PRESET_ROOT}/${path}")
	endforeach()
	juce_add_binary_data(${ARG_TARGET}
		NAMESPACE ${ARG_NAMESPACE}
		HEADER_NAME ${ARG_HEADER_NAME}
		SOURCES ${resourceFiles})
	target_include_directories(${ARG_TARGET} INTERFACE "${generatedDirectory}")
endfunction()
